### ISSUE TITLE
This annoys me.

### ISSUE THREAD

**Issue by Soapy7261** [BlackFurORG/pingernos#26]
Latency and API Latency has no space between the number and ms, but protocol does.
![Screenshot 2023-01-21 133431](https://user-images.githubusercontent.com/81933267/213881975-3914d3eb-e565-46bc-accd-4bc5a3d14a24.png)

**Comment by Dobby-progam** [comment]
https://github.com/BlackFurORG/pingernos/blob/main/src/commands/utility/ping.js#L22
The line of code, and there is a space, I can't create a pull request rn

**Comment by MiataBoy** [comment]
Fixed

**Comment by Soapy7261** [comment]
Thank you.

**Comment by MiataBoy** [comment]
👍🏻
